# Training the convnext model of dominance classification on RCA on a small dataset

# experiment number
exp_number: 2

# dataset folder
dataset_folder: "./datasets/small_main_dataset"

# folder where models will be saved
models_folder: "./models"

# file where the study numbers for the samples in folds are stored
folds_studies_path: "./datasets/small_folds_and_holdout_dict.pkl"

# paths to augmentation configs
transforms_folder: "./train_dominance/transforms.py"

# path to the logs folder
log_path: "./logs"

# which feature folders in the dataset to use, if more than one, write as "normal, occlusion"
features: "normal, occlusion"

# which model to use
model_type: "convnext"

# number of epochs
n_epochs: 7

# device
device: "cuda:1"

# geheral seed
seed: 42

# confidence threshold for decision making of slice classification (circulation type)
conf_thr: 0.5

# threshold of confidence in decision making of projection classification (circulation type)
conf_thr_projection: 0.5

dataset_params:
  # what type of artery to use
  artery_type: "LCA"
  # frequency of occurrence of classes
  proportion_cls:
    - 1
    - 1
  # step through which the slices are taken
  steps:
    - 1
    - 2
  # seed for mixing dataset items
  seed: 42

# optimizer settings
optimizer_settings:
  weight_decay: 0.05
  betas: 
    - 0.9
    - 0.999
  lr: 0.0001

# loss function settings
loss_fn_type: 'NCEandRCE'
loss_fn_settings:
  # number of classes
  num_classes: 2
  # weight
  weight:
    - 3.8
    - 1
  # coefficient for normalized crossentropy
  alpha: 0.3
  # coefficient for reverse crossentropy
  beta: 0.7

# slice selection parameter settings
slice_selection_settings:
  method_num: 1
  model_slice_selection_path: "models/LCA_frames_quality/frames_selection_model_0.83_0.788_1.567.pt"
  conf_thr_slices_left: 0.5
  conf_thr_slices_right: 0.5
  window: 3
  batch_size: 100
  frames_selection_method: "model" # model, ssim, first_frames, None
  n_first_frames_to_skip: 20

test_slice_selection_settings:
  ssim_selection: True
  use_model: True
  method_num: 1
  model_slice_selection_path: "models/LCA_frames_quality/frames_selection_model_0.83_0.788_1.567.pt"
  conf_thr_slices: 0.55
  window: 3

# dataloader parameters
dataloaders_params:
  train_dataloader_params:
    batch_size: 100
    shuffle: false
    pin_memory: true
    num_workers: 16
  val_dataloader_params:
    batch_size: 64
    shuffle: false
    pin_memory: true
    num_workers: 16
  test_dataloader_params:
    batch_size: 64
    shuffle: false
    pin_memory: true
    num_workers: 16