# Training the r3d_18 model of dominance classification on LCA on a small dataset

# experiment number
exp_number: 8

# dataset folder
dataset_folder: "./datasets/small_main_dataset"

# folder where models will be saved
models_folder: "./models"

# file where the study numbers for the samples in folds are stored
folds_studies_path: "./datasets/small_folds_and_holdout_dict.pkl"

# which feature folders in the dataset to use, if more than one, write as "normal, occlusion"
features: "normal, occlusion"

# Which labels, depending on the current task, we are interested in
labels_type: "dominance"

# device
device: "cuda:0"

# general seed
seed: 42

dataset_params:
   # what type of artery to use
  artery_type: "LCA"
  # frequency of occurrence of classes
  proportion_cls:
    - 1
    - 1
  # step through which the slices are taken
  steps:
    - 1
    - 2
  # seed for mixing dataset items
  seed: 42

# slice selection parameter settings
slice_selection_settings:
  method_num: 1
  model_slice_selection_path: "models/LCA_frames_quality/frames_selection_model_0.83_0.788_1.567.pt"
  conf_thr_slices_left: 0.5
  conf_thr_slices_right: 0.5
  window: 3
  batch_size: 100
  frames_selection_method: "model" # model, ssim, first_frames, None
  n_first_frames_to_skip: 20

test_slice_selection_settings:
  ssim_selection: True
  use_model: True
  method_num: 1
  model_slice_selection_path: "models/LCA_frames_quality/frames_selection_model_0.83_0.788_1.567.pt"
  conf_thr_slices: 0.55
  window: 3